name: Kaggle_CNN
channels:
  - defaults
dependencies:
  - blas=1.0=mkl
  - bottleneck=1.4.2=py310h540bb41_1
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.11.4=haa95532_0
  - cairo=1.18.4=he9e932c_0
  - contourpy=1.3.1=py310h214f63a_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - expat=2.7.3=h9214b88_0
  - filelock=3.20.0=py310haa95532_0
  - fontconfig=2.15.0=hd211d86_0
  - fonttools=4.60.1=py310h02ab6af_0
  - freetype=2.13.3=h0620614_0
  - fsspec=2025.10.0=py310h4442805_0
  - gmp=6.3.0=h537511b_0
  - gmpy2=2.2.1=py310h827c3e9_0
  - graphite2=1.3.14=hd77b12b_1
  - harfbuzz=10.2.0=he2f9f60_1
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.1=h6c2663c_0
  - importlib-metadata=8.5.0=py310haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - jinja2=3.1.6=py310haa95532_0
  - joblib=1.5.2=py310haa95532_0
  - jpeg=9f=ha349fce_0
  - kiwisolver=1.4.8=py310h5da7b33_0
  - lcms2=2.16=hb4a4139_0
  - lerc=3.0=hd77b12b_0
  - libabseil=20250127.0=cxx17_h52369b4_0
  - libdeflate=1.17=h2bbff1b_1
  - libffi=3.4.4=hd77b12b_1
  - libglib=2.84.4=hfaec014_0
  - libiconv=1.16=h2bbff1b_3
  - libkrb5=1.21.3=h885b0b7_4
  - libpng=1.6.50=h46444df_0
  - libpq=17.6=h652a1e2_0
  - libprotobuf=5.29.3=h65a231f_1
  - libtiff=4.5.1=hd77b12b_0
  - libtorch=2.6.0=cpu_mkl_hcc61593_106
  - libuv=1.48.0=h827c3e9_0
  - libwebp-base=1.3.2=h3d04722_1
  - libxml2=2.13.9=h6201b9f_0
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - markupsafe=3.0.2=py310h827c3e9_0
  - matplotlib=3.10.6=py310haa95532_1
  - matplotlib-base=3.10.6=py310h43afe63_1
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py310h827c3e9_2
  - mkl_fft=1.3.11=py310h827c3e9_0
  - mkl_random=1.2.8=py310hc64d2fc_0
  - mpc=1.3.1=h827c3e9_0
  - mpfr=4.2.1=h56c3642_0
  - mpmath=1.3.0=py310haa95532_0
  - mysql-common=9.3.0=hf582a5b_3
  - mysql-libs=9.3.0=hc0ebf12_3
  - networkx=3.4.2=py310haa95532_0
  - numexpr=2.11.0=py310hdb065b2_0
  - numpy=2.2.5=py310h5f75535_0
  - numpy-base=2.2.5=py310h23d94f8_0
  - openjpeg=2.5.2=hae555c5_0
  - openssl=3.0.18=h543e019_0
  - opentelemetry-api=1.37.0=py310haa95532_0
  - packaging=25.0=py310haa95532_1
  - pandas=2.3.3=py310h42c1672_1
  - pcre2=10.46=h5740b90_0
  - pillow=11.1.0=py310h096bfcc_0
  - pip=25.2=pyhc872135_1
  - pixman=0.46.4=h4043f72_0
  - pyparsing=3.2.0=py310haa95532_0
  - pyqt=6.7.1=py310h378bd72_2
  - pyqt6-sip=13.9.1=py310h02ab6af_2
  - python=3.10.19=h981015d_0
  - python-dateutil=2.9.0post0=py310haa95532_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - pytorch=2.6.0=cpu_mkl_py310h6e8a95c_106
  - pytz=2025.2=py310haa95532_0
  - qtbase=6.7.3=hd088775_4
  - qtdeclarative=6.7.3=h885b0b7_1
  - qtsvg=6.7.3=h9d4b640_1
  - qttools=6.7.3=hcb596f7_1
  - qtwebchannel=6.7.3=h885b0b7_1
  - qtwebsockets=6.7.3=h885b0b7_1
  - scikit-learn=1.7.2=py310h9296b3f_0
  - scipy=1.15.3=py310h180bac5_0
  - seaborn=0.13.2=py310haa95532_3
  - setuptools=72.1.0=py310haa95532_0
  - sip=6.10.0=py310h5da7b33_0
  - six=1.17.0=py310haa95532_0
  - sleef=3.5.1=h8cc25b3_2
  - sqlite=3.51.0=hda9a48d_0
  - sympy=1.14.0=py310haa95532_0
  - tbb=2021.8.0=h59b6b97_0
  - tbb-devel=2021.8.0=h59b6b97_0
  - threadpoolctl=3.5.0=py310h9909e9c_0
  - tk=8.6.15=hf199647_0
  - tomli=2.2.1=py310haa95532_0
  - tornado=6.5.1=py310h827c3e9_0
  - typing-extensions=4.15.0=py310haa95532_0
  - typing_extensions=4.15.0=py310haa95532_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.42=haa95532_5
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py310haa95532_0
  - xz=5.6.4=h4754444_1
  - zipp=3.21.0=py310haa95532_0
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
prefix: C:\Users\julia\anaconda3\envs\Kaggle_CNN
